# Generated by Django 5.2.15 on 2026-06-07 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='rules.rule')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transactions.transaction')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', '-created_at'], name='alerts_account_41d0dd_idx'), models.Index(fields=['rule'], name='alerts_rule_id_624257_idx'), models.Index(fields=['transaction'], name='alerts_transac_da3e0b_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'transaction'), name='alerts_unique_rule_transaction')],
            },
        ),
    ]
