# Generated by Django 5.2.15 on 2026-06-07 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rule_type', models.CharField(choices=[('LARGE_TRANSACTION', 'Large Transaction'), ('HIGH_FREQUENCY', 'High Frequency')], max_length=30)),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('frequency_limit', models.PositiveIntegerField(default=5)),
                ('window_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to='identity.apiclient')),
            ],
            options={
                'db_table': 'rules',
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='rules_is_acti_4a36db_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount_threshold__gt', 0), ('rule_type', 'LARGE_TRANSACTION')), models.Q(('rule_type', 'LARGE_TRANSACTION'), _negated=True), _connector='OR'), name='rules_large_tx_threshold_positive'), models.CheckConstraint(condition=models.Q(models.Q(('frequency_limit__gt', 0), ('rule_type', 'HIGH_FREQUENCY')), models.Q(('rule_type', 'HIGH_FREQUENCY'), _negated=True), _connector='OR'), name='rules_frequency_limit_positive'), models.CheckConstraint(condition=models.Q(models.Q(('rule_type', 'HIGH_FREQUENCY'), ('window_hours__gt', 0)), models.Q(('rule_type', 'HIGH_FREQUENCY'), _negated=True), _connector='OR'), name='rules_window_hours_positive')],
            },
        ),
    ]
