# Generated by Django 5.2.15 on 2026-06-07 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_transactions', to='identity.apiclient')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account_id', '-timestamp'], name='transaction_account_8c9e8d_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transactions_amount_positive')],
            },
        ),
    ]
